export const audioMap = {
  "Welcome to Estimation!": "/assets/audio/audio_welcome_to_estimation__0.mp3",
  "I'm Spark, your math guide.": "/assets/audio/audio_i_m_spark__your_math_guide__1.mp3",
  "In this lesson, you'll learn how to make super-smart close guesses!": "/assets/audio/audio_in_this_lesson__you_ll_learn_how_to_make_2.mp3",
  "And that's a skill you'll use your whole life.": "/assets/audio/audio_and_that_s_a_skill_you_ll_use_your_whole_3.mp3",
  "Let's go on an adventure!": "/assets/audio/audio_let_s_go_on_an_adventure__4.mp3",
  "Sarah and John are at the book fair.": "/assets/audio/audio_sarah_and_john_are_at_the_book_fair__5.mp3",
  "Sarah has 247 coins. A book costs 189 coins.": "/assets/audio/audio_sarah_has_247_coins__a_book_costs_189_co_6.mp3",
  "She needs to decide fast... does she have enough?": "/assets/audio/audio_she_needs_to_decide_fast____does_she_hav_7.mp3",
  "Watch how she uses a special math trick called estimation!": "/assets/audio/audio_watch_how_she_uses_a_special_math_trick__8.mp3",
  "John and Sarah are helping at Mike's fruit stall at the Saturday market.": "/assets/audio/audio_john_and_sarah_are_helping_at_mike_s_fru_9.mp3",
  "It's a busy day, and there's no time to use paper and pencil!": "/assets/audio/audio_it_s_a_busy_day__and_there_s_no_time_to__10.mp3",
  "Mike says... about how many mangoes have I sold in two days?": "/assets/audio/audio_mike_says____about_how_many_mangoes_have_11.mp3",
  "Sarah says: Remember what Emma taught us? Round first!": "/assets/audio/audio_sarah_says__remember_what_emma_taught_us_12.mp3",
  "Three hundred and eighteen is close to three hundred.": "/assets/audio/audio_three_hundred_and_eighteen_is_close_to_t_13.mp3",
  "Two hundred and fifty-three is close to two hundred and fifty.": "/assets/audio/audio_two_hundred_and_fifty_three_is_close_to__14.mp3",
  "Look at the number line... three eighteen is closer to three hundred than to three fifty. So we round down!": "/assets/audio/audio_look_at_the_number_line____three_eightee_15.mp3",
  "Three hundred plus two hundred and fifty equals five hundred and fifty!": "/assets/audio/audio_three_hundred_plus_two_hundred_and_fifty_16.mp3",
  "Mike sold about five hundred and fifty mangoes total!": "/assets/audio/audio_mike_sold_about_five_hundred_and_fifty_m_17.mp3",
  "The exact answer is five hundred and seventy-one... and our estimate of five fifty is very close!": "/assets/audio/audio_the_exact_answer_is_five_hundred_and_sev_18.mp3",
  "That's the power of estimation!": "/assets/audio/audio_that_s_the_power_of_estimation__19.mp3",
  "Now here's a subtraction challenge.": "/assets/audio/audio_now_here_s_a_subtraction_challenge__20.mp3",
  "John brought four hundred and sixty-two flyers. They gave out one hundred and seventy-nine.": "/assets/audio/audio_john_brought_four_hundred_and_sixty_two__21.mp3",
  "About how many flyers are left? Let's round!": "/assets/audio/audio_about_how_many_flyers_are_left__let_s_ro_22.mp3",
  "Four sixty-two rounds up to five hundred. One seventy-nine rounds up to two hundred.": "/assets/audio/audio_four_sixty_two_rounds_up_to_five_hundred_23.mp3",
  "Five hundred minus two hundred is three hundred!": "/assets/audio/audio_five_hundred_minus_two_hundred_is_three__24.mp3",
  "The exact answer is two hundred and eighty-three.": "/assets/audio/audio_the_exact_answer_is_two_hundred_and_eigh_25.mp3",
  "Our estimate was three hundred... that's really close!": "/assets/audio/audio_our_estimate_was_three_hundred____that_s_26.mp3",
  "Sarah says: Estimation isn't about being perfect... it's about being smart!": "/assets/audio/audio_sarah_says__estimation_isn_t_about_being_27.mp3",
  "And people everywhere use this trick every single day.": "/assets/audio/audio_and_people_everywhere_use_this_trick_eve_28.mp3",
  "Here's the three-step secret:": "/assets/audio/audio_here_s_the_three_step_secret__29.mp3",
  "Step one... round each number.": "/assets/audio/audio_step_one____round_each_number__30.mp3",
  "Step two... add or subtract the rounded numbers.": "/assets/audio/audio_step_two____add_or_subtract_the_rounded__31.mp3",
  "Step three... check! Is your estimate close?": "/assets/audio/audio_step_three____check__is_your_estimate_cl_32.mp3",
  "If yes, you're an estimator! Now let's try it ourselves!": "/assets/audio/audio_if_yes__you_re_an_estimator__now_let_s_t_33.mp3",
  "Welcome to the interactive sandbox!": "/assets/audio/audio_welcome_to_the_interactive_sandbox__34.mp3",
  "Complete all three stations to earn your badge.": "/assets/audio/audio_complete_all_three_stations_to_earn_your_35.mp3",
  "Drag the glowing dot to the round number that this number is closest to.": "/assets/audio/audio_drag_the_glowing_dot_to_the_round_number_36.mp3",
  "Remember — look at which big number it's nearest to on the number line!": "/assets/audio/audio_remember___look_at_which_big_number_it_s_37.mp3",
  "Look at this problem. Round the numbers in your head, then choose the best estimate from the four choices.": "/assets/audio/audio_look_at_this_problem__round_the_numbers__38.mp3",
  "Watch the Estimate-O-Meter!": "/assets/audio/audio_watch_the_estimate_o_meter__39.mp3",
  "Time to build your own estimate!": "/assets/audio/audio_time_to_build_your_own_estimate__40.mp3",
  "First, round each number. Then add or subtract.": "/assets/audio/audio_first__round_each_number__then_add_or_su_41.mp3",
  "You're thinking like a real mathematician!": "/assets/audio/audio_you_re_thinking_like_a_real_mathematicia_42.mp3",
  "Welcome to IntelliPlay!": "/assets/audio/audio_welcome_to_intelliplay__43.mp3",
  "Complete all 10 worlds by solving estimation challenges.": "/assets/audio/audio_complete_all_10_worlds_by_solving_estima_44.mp3",
  "Good luck!": "/assets/audio/audio_good_luck__45.mp3",
  "Amazing work!": "/assets/audio/audio_amazing_work__46.mp3",
  "Before you get your badge, tell me... when might YOU use estimation in real life?": "/assets/audio/audio_before_you_get_your_badge__tell_me____wh_47.mp3",
  "Think about it and write your answer below!": "/assets/audio/audio_think_about_it_and_write_your_answer_bel_48.mp3",
  "Welcome to Estimation Simulations!": "/assets/audio/audio_welcome_to_estimation_simulations__49.mp3",
  "You have three fun challenges to try.": "/assets/audio/audio_you_have_three_fun_challenges_to_try__50.mp3",
  "First, estimate how many objects are in a jar. Then find numbers on a number line. Finally, help a pirate reach hidden treasure!": "/assets/audio/audio_first__estimate_how_many_objects_are_in__51.mp3",
  "Try them all to earn stars!": "/assets/audio/audio_try_them_all_to_earn_stars__52.mp3",
  "Look carefully at the jar and count the objects inside.": "/assets/audio/audio_look_carefully_at_the_jar_and_count_the__53.mp3",
  "Try to spot groups or patterns to help you estimate.": "/assets/audio/audio_try_to_spot_groups_or_patterns_to_help_y_54.mp3",
  "When you are ready, enter your best guess!": "/assets/audio/audio_when_you_are_ready__enter_your_best_gues_55.mp3",
  "A number line helps us see where numbers live between other numbers.": "/assets/audio/audio_a_number_line_helps_us_see_where_numbers_56.mp3",
  "Drag the slider until the marker is exactly where your target number should be.": "/assets/audio/audio_drag_the_slider_until_the_marker_is_exac_57.mp3",
  "There are three levels, each with a bigger range!": "/assets/audio/audio_there_are_three_levels__each_with_a_bigg_58.mp3",
  "A pirate needs your help! Use the grid to estimate the distance to the treasure.": "/assets/audio/audio_a_pirate_needs_your_help__use_the_grid_t_59.mp3",
  "Remember, each square on the map equals ten steps.": "/assets/audio/audio_remember__each_square_on_the_map_equals__60.mp3",
  "Which answer is closest to the real distance?": "/assets/audio/audio_which_answer_is_closest_to_the_real_dist_61.mp3"
};
